kind: PersistentVolume
apiVersion: v1
metadata:
 name: store-persistent-volume
 namespace: jenkins
spec:
 storageClassName: hostpath
 capacity:
  storage: 5Gi
 accessModes:
  - ReadWriteOnce
 hostPath:
  path: "/user/papu/kshare"
